// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2ekGyy9Xoo2oIiL8XnAd24T2VTnB2Hw',
    appId: '1:40973923063:web:6b93666c151a7b23c699f2',
    messagingSenderId: '40973923063',
    projectId: 'qrcode-b7c90',
    authDomain: 'qrcode-b7c90.firebaseapp.com',
    storageBucket: 'qrcode-b7c90.firebasestorage.app',
    measurementId: 'G-HG37KRM22C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw5ea7N8rOtCruOaEqXOsAQoRxuafs5gI',
    appId: '1:40973923063:android:5bd1834f503f4647c699f2',
    messagingSenderId: '40973923063',
    projectId: 'qrcode-b7c90',
    storageBucket: 'qrcode-b7c90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpQaXGuVeVfxsg7A19shw7wtbRWAn1n5M',
    appId: '1:40973923063:ios:d963dfc9cf675edbc699f2',
    messagingSenderId: '40973923063',
    projectId: 'qrcode-b7c90',
    storageBucket: 'qrcode-b7c90.firebasestorage.app',
    iosBundleId: 'com.example.qrCodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpQaXGuVeVfxsg7A19shw7wtbRWAn1n5M',
    appId: '1:40973923063:ios:d963dfc9cf675edbc699f2',
    messagingSenderId: '40973923063',
    projectId: 'qrcode-b7c90',
    storageBucket: 'qrcode-b7c90.firebasestorage.app',
    iosBundleId: 'com.example.qrCodeScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI2ekGyy9Xoo2oIiL8XnAd24T2VTnB2Hw',
    appId: '1:40973923063:web:b0b27fa145895253c699f2',
    messagingSenderId: '40973923063',
    projectId: 'qrcode-b7c90',
    authDomain: 'qrcode-b7c90.firebaseapp.com',
    storageBucket: 'qrcode-b7c90.firebasestorage.app',
    measurementId: 'G-HXMHSTSXK7',
  );
}
